apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name:  faspi-auto
  #namespace: {{ $.Values.global.namespace }}
  namespace: {{.Release.Namespace}}
spec:
  resolver: endpoint
  prefix: /umbrella
  rewrite: /
  service: prod:80
